const TruyenHinhDiDong = [
    
  {
    id: 1,
    goicuoc: "Fiber S1",
    bangthong: "400Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "2Mbps",
    noidung4: "",
    giacuoc: "323.000",
  },
  {
    id: 1,
    goicuoc: "Fiber S2",
    bangthong: "800Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "5Mbps",
    noidung4: "",
    giacuoc: "510.000",
  },
  {
    id: 1,
    goicuoc: "Fiber S3",
    bangthong: "1000Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "12Mbps",
    noidung4: "",
    giacuoc: "629.000",
  },
  {
    id: 1,
    goicuoc: "Fiber Wifi 1",
    bangthong: "400Mbps + 2 Mesh",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "2Mbps",
    noidung4: "",
    giacuoc: "365.500",
  },
  {
    id: 1,
    goicuoc: "Fiber Wifi 2",
    bangthong: "800Mbps + 3 Mesh",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "5Mbps",
    noidung4: "",
    giacuoc: "578.000",
  },
  {
    id: 1,
    goicuoc: "Fiber Wifi 3",
    bangthong: "1000Mbps + 3 Mesh",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "12Mbps",
    noidung4: "",
    giacuoc: "697.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 36+",
    bangthong: "40Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "512Kbps",
    noidung4: "16.2Mbps",
    giacuoc: "168.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 50+",
    bangthong: "80Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "768Kbps",
    noidung4: "20.5Mbps",
    giacuoc: "240.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 60Eco+",
    bangthong: "100Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "Địa chỉ IP LAN Động",
    noidung3: "1Mbps",
    noidung4: "22.8Mbps",
    giacuoc: "288.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 60+",
    bangthong: "100Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "1.5Mbps",
    noidung4: "22.8Mbps",
    giacuoc: "480.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 80Eco+",
    bangthong: "120Mbps",
    noidung1: "Địa chỉ IP WAN Động",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "1.5Mbps",
    noidung4: "28.8Mbps",
    giacuoc: "468.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 80+",
    bangthong: "120Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "3Mbps",
    noidung4: "28.8Mbps",
    giacuoc: "975.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 100Eco+",
    bangthong: "150Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "2Mbps",
    noidung4: "35Mbps",
    giacuoc: "780.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 100+",
    bangthong: "150Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "4Mbps",
    noidung4: "35Mbps",
    giacuoc: "1.625.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 100VIP+",
    bangthong: "150Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "6Mbps",
    noidung4: "35Mbps",
    giacuoc: "2.600.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 150Eco+",
    bangthong: "200Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "4Mbps",
    noidung4: "50Mbps",
    giacuoc: "1.950.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 150+",
    bangthong: "200Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "6Mbps",
    noidung4: "50Mbps",
    giacuoc: "5.200.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 150VIP+",
    bangthong: "200Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "9Mbps",
    noidung4: "50Mbps",
    giacuoc: "6.500.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 200Eco+",
    bangthong: "300Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "5Mbps",
    noidung4: "60Mbps",
    giacuoc: "3.900.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 200+",
    bangthong: "300Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "8Mbps",
    noidung4: "60Mbps",
    giacuoc: "7.150.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 200VIP+",
    bangthong: "300Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "10Mbps",
    noidung4: "60Mbps",
    giacuoc: "9.750.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 300Eco+",
    bangthong: "400Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Địa chỉ IP LAN Tĩnh",
    noidung3: "8Mbps",
    noidung4: "85Mbps",
    giacuoc: "7.800.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 300+",
    bangthong: "400Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "12Mbps",
    noidung4: "85Mbps",
    giacuoc: "9.750.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 300VIP+",
    bangthong: "400Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "15Mbps",
    noidung4: "85Mbps",
    giacuoc: "13.000.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 500Eco+",
    bangthong: "600Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 8 IP LAN Tĩnh",
    noidung3: "10Mbps",
    noidung4: "125Mbps",
    giacuoc: "11.700.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 500+",
    bangthong: "600Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 16 IP LAN Tĩnh",
    noidung3: "18Mbps",
    noidung4: "125Mbps",
    giacuoc: "16.250.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 500VIP+",
    bangthong: "600Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 16 IP LAN Tĩnh",
    noidung3: "25Mbps",
    noidung4: "125Mbps",
    giacuoc: "19.500.000",
  },
  {
    id: 1,
    goicuoc: "Fiber 1000VIP+",
    bangthong: "1000Mbps",
    noidung1: "1 Địa chỉ IP WAN Tĩnh",
    noidung2: "1 Block 16 IP LAN Tĩnh",
    noidung3: "50Mbps",
    noidung4: "200Mbps",
    giacuoc: "35.750.000",
  },
];

export default TruyenHinhDiDong;
